### ISSUE TITLE
如何生成完整的table of content

### ISSUE THREAD

**Issue by hcjamm** [Neoteus/pandoc-export-markdown-to-epub#1]
生成的table 为一个title加两个content

**Comment by Neoteus** [comment]
我不确定到底是什么问题，只能解释一下生成目录的过程：

如果`pandoc`命令加上`--toc`参数，应该会自动将markdown的每一个标题转化为目录项，例如：

输入2个markdown文件，分别为 1.md:

```
# 标题1
## 标题1.1
```

和 2.md:

```
# 标题2
```

输出为 book.epub，目录应该是:

- 标题1
  - 标题1.1
- 标题2

目录一般保存在EPUB压缩包中的nav.xhtml文件中，可以检查一下，看看出了什么问题。

如果还是无法解决，也许你可以截图给我看看。
